import os
import shutil
import yaml
import markdown
from jinja2 import Environment, FileSystemLoader

# Paths
# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__)) # tools/
PROJECT_ROOT = os.path.dirname(BASE_DIR)              # /
CONTENT_DIR = os.path.join(PROJECT_ROOT, 'content')   # content/
OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'docs')       # docs/
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')   # tools/templates/
ASSETS_DIR = os.path.join(BASE_DIR, 'assets')         # tools/assets/

def load_content():
    content = {}
    
    # Load Config
    with open(os.path.join(CONTENT_DIR, 'config.yml'), 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
        
    # Load Markdown files
    md = markdown.Markdown(extensions=['extra', 'smarty'])
    
    files = {
        'summary': 'summary.md',
        'skills': 'skills.md',
        'education': 'education.md',
        'certifications': 'certifications.md',
        'competencies': 'competencies.md',
        'experience': 'experience.md'
    }
    
    for key, filename in files.items():
        with open(os.path.join(CONTENT_DIR, filename), 'r', encoding='utf-8') as f:
            content[key] = md.convert(f.read())
            
    return config, content

def build():
    print("Building site...")

    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Setup Jinja2
    env = Environment(loader=FileSystemLoader(TEMPLATES_DIR))
    template = env.get_template('index.html')
    
    # Load Data
    config, content = load_content()
    
    # Render
    output = template.render(config=config, content=content)
    
    # Add generation signature
    output = "<!-- Generated by tools/build.py -->\n" + output
    
    # Write index.html to Output Docs
    output_path = os.path.join(OUTPUT_DIR, 'index.html')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(output)
    print(f"Generated: {output_path}")

    # Copy CSS
    css_src = os.path.join(ASSETS_DIR, 'styles.css')
    css_dest = os.path.join(OUTPUT_DIR, 'styles.css')
    shutil.copy2(css_src, css_dest)
    print(f"Copied CSS: {css_dest}")

    # Copy PDF Resume (from assets)
    pdf_src = os.path.join(ASSETS_DIR, 'resume.pdf')
    pdf_dest = os.path.join(OUTPUT_DIR, 'resume.pdf')
    if os.path.exists(pdf_src):
        shutil.copy2(pdf_src, pdf_dest)
        print(f"Copied PDF: {pdf_dest}")
    else:
        print("Warning: resume.pdf not found in tools/assets/")
        
    print("Build complete!")

if __name__ == "__main__":
    build()
